# Lists and Arrays in Python

In [1]:
import array
import numpy as np

## Python List

In [2]:
# Liste
my_list = [True, "Hello", 42.0, 420, None]
# datentyp
print([type(val) for val in my_list])
print(my_list)

[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>, <class 'NoneType'>]
[True, 'Hello', 42.0, 420, None]


## Python Array

In [3]:
# liste
my_array_range = list(range(10))
# array
# i = integer
my_array = array.array('i', my_array_range)
print(my_array)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Array Dtypes

1 byte = 8 bit = 2^8 = 256 bit

|  |  |  |  |  |
|-|-|-|-|-|
| Type code | C Type | Python Type | Minimum size in bytes |
| 'b' | signed char | int | 1 |
| 'B' | unsigned char | int | 1 |
| 'u' | wchar_t | Unicode character | 2 |
| 'h' | signed short | int | 2 |
| 'H' | unsigned short | int | 2 |
| 'i' | signed int | int | 2 |
| 'I' | unsigned int | int | 2 |
| 'l' | signed long | int | 4 |
| 'L' | unsigned long | int | 4 |
| 'q' | signed long long | int | 8 |
| 'Q' | unsigned long long | int | 8 |
| 'f' | float | float | 4 |
| 'd' | double | float | 8 |

In [4]:
my_array_range = list(range(10))
my_array = array.array('d', my_array_range)
print(my_array)

array('d', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])


## Numpy Array

NumPy ist das grundlegende Paket für wissenschaftliches Rechnen in Python.
Es ist eine Python-Bibliothek, die ein mehrdimensionales Array-Objekt, verschiedene abgeleitete Objekte und eine Reihe von Routinen für schnelle Operationen auf Arrays bereitstellt.

Den Kern des NumPy-Pakets bildet das ndarray-Objekt.
Dies kapselt n-dimensionale Arrays homogener Datentypen, wobei viele Operationen aus Leistungsgründen in kompiliertem Code ausgeführt werden.

In [5]:
# Hilfsfunktion array
def array_info(array: np.ndarray) -> None:
    print(f"ndim   = dimension:       {array.ndim}")
    print(f"shape  = größe:           {array.shape}")
    print(f"size   = anzahl Elemente: {array.size}")
    print(f"dtype  = datentyp:        {array.dtype}")
    print(f"values = wert:            \n{array}\n")

In [6]:
my_np_array = np.array([1, 4, 2, 5, 3])
array_info(my_np_array)

ndim   = dimension:       1
shape  = größe:           (5,)
size   = anzahl Elemente: 5
dtype  = datentyp:        int64
values = wert:            
[1 4 2 5 3]



In [7]:
my_np_array = np.array([3.14, 4, 2, 3])
array_info(my_np_array)

ndim   = dimension:       1
shape  = größe:           (4,)
size   = anzahl Elemente: 4
dtype  = datentyp:        float64
values = wert:            
[3.14 4.   2.   3.  ]



In [8]:
my_np_array = np.array([1, 2, 3, 4], dtype='float32')
array_info(my_np_array)

ndim   = dimension:       1
shape  = größe:           (4,)
size   = anzahl Elemente: 4
dtype  = datentyp:        float32
values = wert:            
[1. 2. 3. 4.]



## Intrinsic Arrays 

In [9]:
# initialisieren mit 0
my_np_array = np.zeros(shape=10, dtype=int)
array_info(my_np_array)

ndim   = dimension:       1
shape  = größe:           (10,)
size   = anzahl Elemente: 10
dtype  = datentyp:        int64
values = wert:            
[0 0 0 0 0 0 0 0 0 0]



In [10]:
# initialisieren mit 1
my_np_array = np.ones(shape=(3, 5), dtype=float)
array_info(my_np_array)

ndim   = dimension:       2
shape  = größe:           (3, 5)
size   = anzahl Elemente: 15
dtype  = datentyp:        float64
values = wert:            
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



In [11]:
# initialisieren mit 3.14
my_np_array = np.full(shape=(3, 5), fill_value=3.14)
array_info(my_np_array)

ndim   = dimension:       2
shape  = größe:           (3, 5)
size   = anzahl Elemente: 15
dtype  = datentyp:        float64
values = wert:            
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]



In [12]:
# initialisieren mit 0 bis 20
my_np_array = np.arange(start=0, stop=22, step=2)
array_info(my_np_array)

ndim   = dimension:       1
shape  = größe:           (11,)
size   = anzahl Elemente: 11
dtype  = datentyp:        int64
values = wert:            
[ 0  2  4  6  8 10 12 14 16 18 20]



In [13]:
my_np_array = np.linspace(start=0, stop=1, num=5)
array_info(my_np_array)

ndim   = dimension:       1
shape  = größe:           (5,)
size   = anzahl Elemente: 5
dtype  = datentyp:        float64
values = wert:            
[0.   0.25 0.5  0.75 1.  ]



In [14]:
# Einheitsmatrix
my_np_array = np.eye(N=3)
array_info(my_np_array)

ndim   = dimension:       2
shape  = größe:           (3, 3)
size   = anzahl Elemente: 9
dtype  = datentyp:        float64
values = wert:            
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [15]:
# Hauptdiagonale 
my_np_array = np.diag([1, 2, 3])
array_info(my_np_array)

ndim   = dimension:       2
shape  = größe:           (3, 3)
size   = anzahl Elemente: 9
dtype  = datentyp:        int64
values = wert:            
[[1 0 0]
 [0 2 0]
 [0 0 3]]



## Random Functions

In [16]:
# Zufall von 0 bis 9
my_np_array = np.random.randint(low=0, high=10, size=(3, 3))
array_info(my_np_array)

ndim   = dimension:       2
shape  = größe:           (3, 3)
size   = anzahl Elemente: 9
dtype  = datentyp:        int64
values = wert:            
[[1 2 3]
 [5 3 7]
 [7 3 8]]



In [17]:
my_np_array = np.random.random(size=(3, 3))
array_info(my_np_array)

ndim   = dimension:       2
shape  = größe:           (3, 3)
size   = anzahl Elemente: 9
dtype  = datentyp:        float64
values = wert:            
[[0.41516008 0.1746346  0.23598043]
 [0.39312202 0.97883348 0.96946356]
 [0.63155491 0.3717253  0.76949921]]

