# Numpy Basics

NumPy bietet einen N-dimensionalen Array-Typ, den ndarray, der eine Sammlung von „Elementen“ des *gleichen* Typs beschreibt.
Die Elemente können unter Verwendung von beispielsweise N ganzen Zahlen indiziert werden.
Alle ndarrays sind homogen: Jedes Element nimmt einen gleich großen Speicherblock ein, und alle Blöcke werden genau gleich interpretiert.
Ein aus einem Array extrahiertes Element, z. B. durch Indizierung, wird durch ein Python-Objekt dargestellt, dessen Typ einer der in NumPy erstellten skalaren Array-Typen ist.

<p align="center">
<img src="https://numpy.org/doc/stable/_images/threefundamental.png">
</p>

## NumPy Array Attributes

In [43]:
import numpy as np
np.random.seed(0)

In [44]:
# Hilfsfunktion array
def array_info(array: np.ndarray) -> None:
    print(f"ndim   = dimension:       {array.ndim}")
    print(f"shape  = größe:           {array.shape}")
    print(f"size   = anzahl Elemente: {array.size}")
    print(f"dtype  = datentyp:        {array.dtype}")
    print(f"values = wert:            \n{array}\n")

## Array Indexing and Slicing

Array-Indizierung bezieht sich auf jede Verwendung der eckigen Klammern ([]) zum Indexieren von Array-Werten. Es gibt viele Optionen für die Indexierung, die der numpy-Indexierung eine große Macht verleihen.

Die meisten der folgenden Beispiele zeigen die Verwendung der Indizierung beim Verweisen auf Daten in einem Array. Die Beispiele funktionieren genauso gut, wenn Sie einem Array zuweisen.

Beachten Sie, dass Slices von Arrays nicht die internen Array-Daten kopieren, sondern nur neue Ansichten der Originaldaten erzeugen.

![](../media/np_matrix_indexing.png)

<p align="center">
<img src="https://numpy.org/doc/stable/_images/np_indexing.png">
</p>

<p align="center">
<img src="https://numpy.org/doc/stable/_images/np_matrix_indexing.png">
</p>

In [45]:
data = np.array([[1, 2], [3, 4], [5, 6]])

array_info(data)

ndim   = dimension:       2
shape  = größe:           (3, 2)
size   = anzahl Elemente: 6
dtype  = datentyp:        int64
values = wert:            
[[1 2]
 [3 4]
 [5 6]]



In [46]:
print(data[:3])

[[1 2]
 [3 4]
 [5 6]]


In [47]:
print(data[1:])

[[3 4]
 [5 6]]


In [48]:
print(data[1:2])

[[3 4]]


In [49]:
print(data[::-1])

[[5 6]
 [3 4]
 [1 2]]


In [50]:
print(data[0, :])

[1 2]


In [51]:
print(data[0])

[1 2]


In [52]:
print(data[:, 0])

[1 3 5]


In [53]:
mean = [0, 0]
cov = [[1, 2],
       [2, 5]]

data = np.random.multivariate_normal(mean=mean, cov=cov, size=10)

print(data)
print(data.shape)

[[-1.78290539 -3.87118733]
 [-1.76178869 -1.82780883]
 [-1.35141055 -4.32039163]
 [-0.81984535 -2.14310962]
 [-0.06176746  0.29530878]
 [-0.68960528 -0.09076013]
 [-0.74967019 -1.67816385]
 [-0.53776779 -0.93711981]
 [-1.30183841 -3.36497764]
 [ 0.03761145 -0.8336645 ]]
(10, 2)


In [54]:
rand_idxs = np.random.randint(low=0, high=data.shape[0], size=3)

print(rand_idxs)

[9 9 0]


In [55]:
x_subsample = data[rand_idxs, :]

print(x_subsample)

[[ 0.03761145 -0.8336645 ]
 [ 0.03761145 -0.8336645 ]
 [-1.78290539 -3.87118733]]


In [56]:
x_subsample = data[rand_idxs]

print(x_subsample)

[[ 0.03761145 -0.8336645 ]
 [ 0.03761145 -0.8336645 ]
 [-1.78290539 -3.87118733]]


## Subarrays are views

In [57]:
print(data)

[[-1.78290539 -3.87118733]
 [-1.76178869 -1.82780883]
 [-1.35141055 -4.32039163]
 [-0.81984535 -2.14310962]
 [-0.06176746  0.29530878]
 [-0.68960528 -0.09076013]
 [-0.74967019 -1.67816385]
 [-0.53776779 -0.93711981]
 [-1.30183841 -3.36497764]
 [ 0.03761145 -0.8336645 ]]


In [58]:
x_sub_array = data[:2, :2]

array_info(x_sub_array)

ndim   = dimension:       2
shape  = größe:           (2, 2)
size   = anzahl Elemente: 4
dtype  = datentyp:        float64
values = wert:            
[[-1.78290539 -3.87118733]
 [-1.76178869 -1.82780883]]



In [59]:
x_sub_array[0, 0] = -1

array_info(x_sub_array)

ndim   = dimension:       2
shape  = größe:           (2, 2)
size   = anzahl Elemente: 4
dtype  = datentyp:        float64
values = wert:            
[[-1.         -3.87118733]
 [-1.76178869 -1.82780883]]



In [60]:
array_info(data)

ndim   = dimension:       2
shape  = größe:           (10, 2)
size   = anzahl Elemente: 20
dtype  = datentyp:        float64
values = wert:            
[[-1.         -3.87118733]
 [-1.76178869 -1.82780883]
 [-1.35141055 -4.32039163]
 [-0.81984535 -2.14310962]
 [-0.06176746  0.29530878]
 [-0.68960528 -0.09076013]
 [-0.74967019 -1.67816385]
 [-0.53776779 -0.93711981]
 [-1.30183841 -3.36497764]
 [ 0.03761145 -0.8336645 ]]



## Creating copies of arrays

In [61]:
x_copy = data[:2, :2].copy()

array_info(x_copy)

ndim   = dimension:       2
shape  = größe:           (2, 2)
size   = anzahl Elemente: 4
dtype  = datentyp:        float64
values = wert:            
[[-1.         -3.87118733]
 [-1.76178869 -1.82780883]]



In [62]:
x_copy[0, 0] = 42

array_info(x_copy)

ndim   = dimension:       2
shape  = größe:           (2, 2)
size   = anzahl Elemente: 4
dtype  = datentyp:        float64
values = wert:            
[[42.         -3.87118733]
 [-1.76178869 -1.82780883]]



In [63]:
array_info(data)

ndim   = dimension:       2
shape  = größe:           (10, 2)
size   = anzahl Elemente: 20
dtype  = datentyp:        float64
values = wert:            
[[-1.         -3.87118733]
 [-1.76178869 -1.82780883]
 [-1.35141055 -4.32039163]
 [-0.81984535 -2.14310962]
 [-0.06176746  0.29530878]
 [-0.68960528 -0.09076013]
 [-0.74967019 -1.67816385]
 [-0.53776779 -0.93711981]
 [-1.30183841 -3.36497764]
 [ 0.03761145 -0.8336645 ]]



## Reshaping of Arrays

<p align="center">
<img src="https://numpy.org/doc/stable/_images/np_reshape.png">
</p>

In [64]:
a = np.arange(start=1, stop=10)

array_info(a)

ndim   = dimension:       1
shape  = größe:           (9,)
size   = anzahl Elemente: 9
dtype  = datentyp:        int64
values = wert:            
[1 2 3 4 5 6 7 8 9]



In [65]:
grid = np.reshape(a, newshape=(3, 3))

array_info(grid)

ndim   = dimension:       2
shape  = größe:           (3, 3)
size   = anzahl Elemente: 9
dtype  = datentyp:        int64
values = wert:            
[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [66]:
data = np.array([1, 2, 3])

array_info(data)

ndim   = dimension:       1
shape  = größe:           (3,)
size   = anzahl Elemente: 3
dtype  = datentyp:        int64
values = wert:            
[1 2 3]



In [67]:
data = np.reshape(data, newshape=(1, 3))

array_info(data)

ndim   = dimension:       2
shape  = größe:           (1, 3)
size   = anzahl Elemente: 3
dtype  = datentyp:        int64
values = wert:            
[[1 2 3]]



In [68]:
array_info(data)

data = data[np.newaxis, :]

array_info(data)

ndim   = dimension:       2
shape  = größe:           (1, 3)
size   = anzahl Elemente: 3
dtype  = datentyp:        int64
values = wert:            
[[1 2 3]]

ndim   = dimension:       3
shape  = größe:           (1, 1, 3)
size   = anzahl Elemente: 3
dtype  = datentyp:        int64
values = wert:            
[[[1 2 3]]]



In [69]:
array_info(data)

data = data.reshape((3, 1))

array_info(data)

ndim   = dimension:       3
shape  = größe:           (1, 1, 3)
size   = anzahl Elemente: 3
dtype  = datentyp:        int64
values = wert:            
[[[1 2 3]]]

ndim   = dimension:       2
shape  = größe:           (3, 1)
size   = anzahl Elemente: 3
dtype  = datentyp:        int64
values = wert:            
[[1]
 [2]
 [3]]



In [70]:
array_info(data)

data = data.ravel()

array_info(data)

ndim   = dimension:       2
shape  = größe:           (3, 1)
size   = anzahl Elemente: 3
dtype  = datentyp:        int64
values = wert:            
[[1]
 [2]
 [3]]

ndim   = dimension:       1
shape  = größe:           (3,)
size   = anzahl Elemente: 3
dtype  = datentyp:        int64
values = wert:            
[1 2 3]



In [71]:
data = data.reshape((3, 1))
array_info(data)

data = data.flatten()

array_info(data)

ndim   = dimension:       2
shape  = größe:           (3, 1)
size   = anzahl Elemente: 3
dtype  = datentyp:        int64
values = wert:            
[[1]
 [2]
 [3]]

ndim   = dimension:       1
shape  = größe:           (3,)
size   = anzahl Elemente: 3
dtype  = datentyp:        int64
values = wert:            
[1 2 3]



### “Automatic” Reshaping

In [72]:
a = np.arange(30)

array_info(a)

ndim   = dimension:       1
shape  = größe:           (30,)
size   = anzahl Elemente: 30
dtype  = datentyp:        int64
values = wert:            
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]



In [73]:
b = a.reshape((2, -1, 3))

array_info(b)

ndim   = dimension:       3
shape  = größe:           (2, 5, 3)
size   = anzahl Elemente: 30
dtype  = datentyp:        int64
values = wert:            
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]



## Changing the Dtype

| Numpy type | C type   | Description |
|-|-|-|
| numpy.int8 | int8_t | Byte (-128 to 127) |
| numpy.int16 | int16_t |   Integer (-32768 to 32767) |
| numpy.int32 | int32_t |   Integer (-2147483648 to 2147483647) |
| numpy.int64 | int64_t |   Integer (-9223372036854775808 to 9223372036854775807) |
| numpy.uint8 | uint8_t |   Unsigned integer (0 to 255) |
| numpy.uint16 | uint16_t |   Unsigned integer (0 to 65535) |
| numpy.uint32 | uint32_t |   Unsigned integer (0 to 4294967295) |
| numpy.uint64 | uint64_t |   Unsigned integer (0 to 18446744073709551615) |
| numpy.intp | intptr_t |   Integer used for indexing, typically the same as ssize_t |
| numpy.uintp | uintptr_t |   Integer large enough to hold a pointer |
| numpy.float32 | float |  |
| numpy.float64 | double |   Note that this matches the precision of the builtin python float. |
| numpy.complex64 | float complex |   Complex number, represented by two 32-bit floats. |
| numpy.complex128 | double complex |   Note that this matches the precision of the builtin python complex. |

In [74]:
data = np.float32([-1.0, 2.0, 3.0])

array_info(data)

ndim   = dimension:       1
shape  = größe:           (3,)
size   = anzahl Elemente: 3
dtype  = datentyp:        float32
values = wert:            
[-1.  2.  3.]



In [75]:
data = np.array([-1.0, 2.0, 3.0], dtype=np.float32)

In [76]:
y = data.astype(np.int8)

array_info(y)

ndim   = dimension:       1
shape  = größe:           (3,)
size   = anzahl Elemente: 3
dtype  = datentyp:        int8
values = wert:            
[-1  2  3]



In [77]:
z = np.uint16(data)

array_info(z)

ndim   = dimension:       1
shape  = größe:           (3,)
size   = anzahl Elemente: 3
dtype  = datentyp:        uint16
values = wert:            
[65535     2     3]



## Concatenation of arrays

In [78]:
# aneinanderhängen
data = np.array([1, 2, 3])
y = np.array([3, 2, 1])

result = np.concatenate([data, y])

array_info(result)

ndim   = dimension:       1
shape  = größe:           (6,)
size   = anzahl Elemente: 6
dtype  = datentyp:        int64
values = wert:            
[1 2 3 3 2 1]



In [79]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

array_info(grid)

ndim   = dimension:       2
shape  = größe:           (2, 3)
size   = anzahl Elemente: 6
dtype  = datentyp:        int64
values = wert:            
[[1 2 3]
 [4 5 6]]



In [80]:
result = np.concatenate([grid, grid])

array_info(result)

ndim   = dimension:       2
shape  = größe:           (4, 3)
size   = anzahl Elemente: 12
dtype  = datentyp:        int64
values = wert:            
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]



In [81]:
result = np.concatenate([grid, grid], axis=0)

array_info(result)

ndim   = dimension:       2
shape  = größe:           (4, 3)
size   = anzahl Elemente: 12
dtype  = datentyp:        int64
values = wert:            
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]



In [82]:
result = np.concatenate([grid, grid], axis=1)

array_info(result)

ndim   = dimension:       2
shape  = größe:           (2, 6)
size   = anzahl Elemente: 12
dtype  = datentyp:        int64
values = wert:            
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]



In [83]:
data = np.array([1, 2, 3])
grid = np.array([[4, 5, 6],
                 [7, 8, 9]])

result = np.vstack([data, grid])

array_info(result)

ndim   = dimension:       2
shape  = größe:           (3, 3)
size   = anzahl Elemente: 9
dtype  = datentyp:        int64
values = wert:            
[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [84]:
y = np.array([[-1], [-1]])

result = np.hstack([grid, y])

array_info(result)

ndim   = dimension:       2
shape  = größe:           (2, 4)
size   = anzahl Elemente: 8
dtype  = datentyp:        int64
values = wert:            
[[ 4  5  6 -1]
 [ 7  8  9 -1]]

